# VAXP TUI Display Manager Configuration

[General]
# Path to the pre-blurred background image (absolute path)
background_path = /home/x/.config/vaxp/background

# Default session to select if none was chosen previously
default_session = aether

# Enable autologin (true/false)
autologin = false
autologin_user = x

[Theme]
# Hex colors for the interface (RGB)
color_title = #cba6f7
color_focus = #89b4fa
color_inactive = #7f8c8d
color_status = #f9e2af
